### ISSUE TITLE
Enable true hierarchical graphs

### ISSUE THREAD

**Issue by Qrious** [uu-cubitt/graph#1]
Currently the `GraphInterface` does not allow the creation of true hierarchical graphs (i.e: `Model` being an element inside another `Model` and this might be multiple levels deep).

In order to implement this, changes to the following files are required:
- `GraphInterface.ts`
- `Graph.ts`
- `AbstractElement.ts`

On first sight, this change appears to influence the `GraphInterface`, Serialization, Deserialization and Delete logic. Additional tests should be added to ensure correctnes of the internal elements.

**Comment by Scurio** [comment]
![graph-structure](https://cloud.githubusercontent.com/assets/15999029/12701448/e4c2a73e-c809-11e5-8bfd-991145a05f74.png)
The current structure (as seen above) does not allow for true hierarchical graphs/models yet.

**Comment by Qrious** [comment]
Resolved in version 1.0.0
