### ISSUE TITLE
Update to encorporate latest version of the template

### ISSUE THREAD

**Issue by Scurio** [uu-cubitt/graph#2]
see template at:
[uu-cubitt/template](https://github.com/uu-cubitt/template)

main focus points:
- updated tslint.json
- updated npm run lint script
- add more badges in the readme

**Comment by Scurio** [comment]
Other focus points:
- update .gitignore
- add.travis.yml
- add .codeclimate.yml
- add .npmignore
- add LICENSE
- add changelog.md
- upgrade to typings over deprecated tsd
- update tsconfig.json to not use files, filesGlob and atom anymore (allows for easier working with editors other than atom)
- update tsconfig.json with extra flags

**Comment by Qrious** [comment]
@Scurio I believe this task is completed?
